export const  AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const  AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const  AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';
export const  ELIMINAR_PRODUCTO_EXITO = 'ELIMINAR_PRODUCTO_EXITO';
export const  ELIMINAR_PRODUCTO_ERROR = 'ELIMINAR_PRODUCTO_ERROR';