export const  COMENZAR_DESCARGA_PRODUCTO = 'COMENZAR_DESCARGA_PRODUCTO';
export const  DESCARGA_PRODUCTO_EXITO = 'DESCARGA_PRODUCTO_EXITO';
export const  DESCARGA_PRODUCTO_ERROR = 'DESCARGA_PRODUCTO_ERROR';